services:
  - type: web
    name: ghhf-dhhf-simulator
    runtime: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
